### PR TITLE
Refactor + Add publications, software, specs ...

### PR DESCRIPTION
**Pull request by ajuvercr**
Refactor:
- move pages inside ./pages/
- move icons inside ./pages/icons
- Deduplicate CSS styles (configure colors inside header)

Add publications:
- Change the publications template to use the information provided by the _configuration file
- Add 'Describing a network of live datasets with the SDS vocabulary' and 'Linked Data Event Streams in Solid containers'

Add Software:
- [x] LDES in LDP package
- [x] TODO: connector architecture things

Add Specs:
- [x] Writing Linked Data Event Streams in LDP Basic Containers specification
- [x] TODO: add SDS spec

Feel free to leave any remarks on structure/layout. 
If the difference between the tree site and the LDES site is not well maintained please leave a comment.

### CODE REVIEW

**Comment by ajuvercr** [comment]
Note that `/demo/autocompletion/` is still outdated because it is not part of this repo.

**Comment by pietercolpaert** [comment]
Damn @ajuvercr @woutslabbinck I love this PR!

One small comment: isn’t the LDES in LDP more of a spec publication rather than a core publication?

**Review by pietercolpaert — CHANGES_REQUESTED** [review]
* [x] LDES in LDP = spec publication?
 * [x] Too many things in the LDES page header are in a bold face → let’s remove the new class from the links?

**Comment by ajuvercr** [comment]
I left the 'new' classes, not because those links are 'new' but because they are links to another site, this gives a visual indication of this. Maybe we can find a middle ground, keeping the grey background, but removing the bold font.

**Pull request merged**
